import Head from 'next/head'
import Image from 'next/image'
import { useGithubUser } from '../hooks/useGithubUser'
import styles from '../styles/Home.module.css'

export default function Home() {
  const { repos, isError, isLoading } = useGithubUser();

  console.log(repos);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ul>
        {repos?.map((repo: any) => (
          <li key={repo.id}>{repo.name}</li>
        ))}
      </ul>
    </div>
  )
}
